---
- name: Install required packages
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - acl
    - gpg
    - sqlite3
    - fish
    - bash-completion
    - lnav

- name: "Set fish as the default shell for {{ansible_user}}"
  become: yes
  ansible.builtin.user:
    shell: /usr/bin/fish
    name: "{{ansible_user}}"
