---
- name: Ensure group "docker" exists
  become: yes
  ansible.builtin.group:
    name: docker
    state: present

- name: Install Docker dependencies
  become: yes
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - gnupg
    - lsb-release

- name: Add Docker's official GPG key
  become: yes
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  tags:
    - never

- name: Add Docker repository
  become: yes
  apt_repository:
    repo: "deb [arch={{OS_ARCHITECTURE}} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{OS_ID}} {{OS_VERSION_CODENAME}} stable"
    state: present

- name: Install Docker
  become: yes
  ansible.builtin.apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: Start Docker service and set it to start on boot
  service:
    name: docker
    state: started
    enabled: yes

- name: Install docker-compose
  become: yes
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{DOCKER_COMPOSE_VERSION}}/docker-compose-linux-{{BUILD_ARCHITECTURE}}"
    dest: /usr/local/bin/docker-compose
    mode: u+x,g+x,o+x

- name: Create network (ignores errors; check carefully if this task returns an error)
  become: yes
  ansible.builtin.shell: |
    docker network create {{docker.network}}
  ignore_errors: yes
