---
- name: Ensure user groups exist
  become: yes
  ansible.builtin.group:
    name: "{{item}}"
    state: present
  with_items: "{{user_groups}}"

- name: Create user "{{name}}"
  become: yes
  ansible.builtin.user:
    name: "{{name}}"
    groups: "{{user_groups}}"
    state: present
    home: "{{home}}"
    system: true
